import FilterHeader from "@/components/FilterHeader/FilterHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CharectersLayout({ children }) {
  return (
    <>
        {children}
    </>
  );
}